/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sauravyash.catalogueviewer.LoginPanel;

import com.sauravyash.catalogueviewer.CatalogueViewer;
import com.sauravyash.catalogueviewer.CatalogueWindow.Utilities;
import com.sauravyash.catalogueviewer.userdatabase.UserAlreadyExistsException;
import com.sauravyash.catalogueviewer.userdatabase.UserDatabase;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.regex.Matcher; 
import java.util.regex.Pattern;

/**
 *
 * @author Yash
 */

public class LoginWindowFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginWindow
     */
    public LoginWindowFrame() {
        initComponents();
        this.pack();
        this.setSize(350, 250);
        CenterWindow();
        LoginInvalidLabel.setVisible(false);
        RegisterPanel.setVisible(false);
        // System.out.println(this.getX() + " and " +  this.getY());
        
        LoginPasswordField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if(e.getKeyCode() == KeyEvent.VK_ENTER) {
                   Login();
                }
            }
        });
        
    }
    
    
    
    private void CenterWindow() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((dim.width - this.getSize().width) / 2, (dim.height - this.getSize().height) / 2);
    }
    
    private void Login(){
        String username = LoginUsernameField.getText();
        String pwd = LoginPasswordField.getText();
        
        if (UserDatabase.IsUserValid(username, pwd)){
            LoginInvalidLabel.setVisible(false);
            System.out.println("login successful");
            CatalogueViewer.OpenSelectorWindow();
            this.dispose();
        } else {
            LoginInvalidLabel.setVisible(true);
            System.out.println("login not very succ");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        HeadingLabel = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        LoginUsername = new javax.swing.JLabel();
        LoginPassword = new javax.swing.JLabel();
        LoginUsernameField = new javax.swing.JTextField();
        LoginPasswordField = new javax.swing.JPasswordField();
        OpenRegisterPanelButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();
        LoginInvalidLabel = new javax.swing.JLabel();
        RegisterPanel = new javax.swing.JPanel();
        RegisterFirstNameLabel = new javax.swing.JLabel();
        RegisterPasswordLabel = new javax.swing.JLabel();
        RegisterFirstNameField = new javax.swing.JTextField();
        RegisterPasswordField = new javax.swing.JPasswordField();
        OpenLoginPageButton = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        RegisterEmailField = new javax.swing.JTextField();
        RegisterEmailLabel = new javax.swing.JLabel();
        RegisterLastNameLabel = new javax.swing.JLabel();
        RegisterLastNameField = new javax.swing.JTextField();
        RegisterUserNameField = new javax.swing.JTextField();
        RegisterUserNameLabel = new javax.swing.JLabel();
        RegisterFailureLabel = new javax.swing.JLabel();
        RegisterSuccessLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EnterKeyPress(evt);
            }
        });
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWeights = new double[] {1.0};
        layout.rowWeights = new double[] {2.0};
        getContentPane().setLayout(layout);

        HeadingLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        HeadingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeadingLabel.setText("Catalogue Viewer");
        HeadingLabel.setFocusable(false);
        HeadingLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        getContentPane().add(HeadingLabel, gridBagConstraints);

        LoginPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LoginPanel.setLayout(new java.awt.GridBagLayout());

        LoginUsername.setText("Username:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        LoginPanel.add(LoginUsername, gridBagConstraints);

        LoginPassword.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        LoginPanel.add(LoginPassword, gridBagConstraints);

        LoginUsernameField.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 20);
        LoginPanel.add(LoginUsernameField, gridBagConstraints);

        LoginPasswordField.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 20);
        LoginPanel.add(LoginPasswordField, gridBagConstraints);

        OpenRegisterPanelButton.setText("Register Page");
        OpenRegisterPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenRegisterPanelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        LoginPanel.add(OpenRegisterPanelButton, gridBagConstraints);

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        LoginPanel.add(LoginButton, gridBagConstraints);

        LoginInvalidLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        LoginInvalidLabel.setForeground(new java.awt.Color(255, 51, 51));
        LoginInvalidLabel.setText("The Username and/or password is incorrect.");
        LoginInvalidLabel.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        LoginPanel.add(LoginInvalidLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(LoginPanel, gridBagConstraints);

        RegisterPanel.setLayout(new java.awt.GridBagLayout());

        RegisterFirstNameLabel.setText("First Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 2);
        RegisterPanel.add(RegisterFirstNameLabel, gridBagConstraints);

        RegisterPasswordLabel.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 2);
        RegisterPanel.add(RegisterPasswordLabel, gridBagConstraints);

        RegisterFirstNameField.setToolTipText("");
        RegisterFirstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterFirstNameFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 20);
        RegisterPanel.add(RegisterFirstNameField, gridBagConstraints);

        RegisterPasswordField.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 20);
        RegisterPanel.add(RegisterPasswordField, gridBagConstraints);

        OpenLoginPageButton.setText("Login Page");
        OpenLoginPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenLoginPageButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        RegisterPanel.add(OpenLoginPageButton, gridBagConstraints);

        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        RegisterPanel.add(RegisterButton, gridBagConstraints);

        RegisterEmailField.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 20);
        RegisterPanel.add(RegisterEmailField, gridBagConstraints);

        RegisterEmailLabel.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 2);
        RegisterPanel.add(RegisterEmailLabel, gridBagConstraints);

        RegisterLastNameLabel.setText("Last Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 2);
        RegisterPanel.add(RegisterLastNameLabel, gridBagConstraints);

        RegisterLastNameField.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 20);
        RegisterPanel.add(RegisterLastNameField, gridBagConstraints);

        RegisterUserNameField.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 20);
        RegisterPanel.add(RegisterUserNameField, gridBagConstraints);

        RegisterUserNameLabel.setText("Username:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 2);
        RegisterPanel.add(RegisterUserNameLabel, gridBagConstraints);

        RegisterFailureLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        RegisterFailureLabel.setForeground(new java.awt.Color(255, 0, 51));
        RegisterFailureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterFailureLabel.setText("Registeration was unsuccessful!");
        RegisterFailureLabel.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        RegisterPanel.add(RegisterFailureLabel, gridBagConstraints);

        RegisterSuccessLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        RegisterSuccessLabel.setForeground(new java.awt.Color(51, 204, 0));
        RegisterSuccessLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterSuccessLabel.setText("You have successfully registered!");
        RegisterSuccessLabel.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        RegisterPanel.add(RegisterSuccessLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(RegisterPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        Login();
    }//GEN-LAST:event_LoginButtonActionPerformed
    
    private boolean validateEmail(String emailStr) {
        Pattern VALID_EMAIL_ADDRESS_REGEX = 
            Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
        Matcher matcher = VALID_EMAIL_ADDRESS_REGEX.matcher(emailStr);
        return matcher.find();
    }
    
    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        String fn = RegisterFirstNameField.getText();
        String ln = RegisterLastNameField.getText();
        String email = RegisterEmailField.getText();
        String username = RegisterUserNameField.getText();
        String pwd = RegisterPasswordField.getText();
        
        try {
            if (fn.length() < 2) {
                throw new IllegalArgumentException("fn");
            } else if (ln.length() < 2) {
                throw new IllegalArgumentException("ln");
            } else if ((email.length() < 5) || !validateEmail(email)) {
                throw new IllegalArgumentException("email");
            } else if (username.length() < 3) {
                throw new IllegalArgumentException("username");
            } else if (pwd.length() < 6) {
                throw new IllegalArgumentException("pwd");
            }
            
            UserDatabase.AddUser(fn, ln, email, username, pwd);
            RegisterSuccessLabel.setVisible(true);
            RegisterFailureLabel.setVisible(false);
            
            
            Utilities.setTimeout(() -> OpenLoginPage(), 2);
           
        } 
        catch (UserAlreadyExistsException e) {
            RegisterSuccessLabel.setVisible(false);
            RegisterFailureLabel.setVisible(true);
            RegisterFailureLabel.setText("The Username chosen is not available. Please use another username.");
            System.out.println("Registration Failure: "+ e);
        } 
        catch (IllegalArgumentException e) {
            RegisterSuccessLabel.setVisible(false);
            RegisterFailureLabel.setVisible(true);
            if(e.getMessage() !=  null) switch (e.getMessage()) {
                case "fn":
                    RegisterFailureLabel.setText("First name is invalid!");
                    break;
                case "ln":
                    RegisterFailureLabel.setText("Last name is invalid!");
                    break;
                case "email":
                    RegisterFailureLabel.setText("Email is invalid!");
                    break;
                case "username":
                    RegisterFailureLabel.setText("Username is unavailable!");
                    break;
                case "pwd":
                    RegisterFailureLabel.setText("Password is not allowed!");
                    break;
                default:
                    break;
            }
        } catch (Exception e){
            RegisterSuccessLabel.setVisible(false);
            RegisterFailureLabel.setVisible(true);
            System.out.println("Registration Failure: "+ e );
            RegisterFailureLabel.setText("Registeration was unsuccessful!");
        }
        
        
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void OpenLoginPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenLoginPageButtonActionPerformed
        OpenLoginPage();
    }//GEN-LAST:event_OpenLoginPageButtonActionPerformed
    
    private void OpenLoginPage(){
        RegisterPanel.setVisible(false);
        LoginPanel.setVisible(true);
        this.setSize(350, 250);
        CenterWindow();
    }
    
    private void OpenRegisterPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenRegisterPanelButtonActionPerformed
        LoginPanel.setVisible(false);
        RegisterPanel.setVisible(true);
        this.setSize(350, 400);
        CenterWindow();
        RegisterSuccessLabel.setVisible(false);
        RegisterFailureLabel.setVisible(false);
    }//GEN-LAST:event_OpenRegisterPanelButtonActionPerformed

    private void RegisterFirstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterFirstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterFirstNameFieldActionPerformed

    private void EnterKeyPress(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EnterKeyPress
        // TODO add your handling code here:
        
    }//GEN-LAST:event_EnterKeyPress

    /** 
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginWindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginWindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginWindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginWindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginWindowFrame().setVisible(true);
//            }
//        });
//    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HeadingLabel;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginInvalidLabel;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel LoginPassword;
    private javax.swing.JPasswordField LoginPasswordField;
    private javax.swing.JLabel LoginUsername;
    private javax.swing.JTextField LoginUsernameField;
    private javax.swing.JButton OpenLoginPageButton;
    private javax.swing.JButton OpenRegisterPanelButton;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JTextField RegisterEmailField;
    private javax.swing.JLabel RegisterEmailLabel;
    private javax.swing.JLabel RegisterFailureLabel;
    private javax.swing.JTextField RegisterFirstNameField;
    private javax.swing.JLabel RegisterFirstNameLabel;
    private javax.swing.JTextField RegisterLastNameField;
    private javax.swing.JLabel RegisterLastNameLabel;
    private javax.swing.JPanel RegisterPanel;
    private javax.swing.JPasswordField RegisterPasswordField;
    private javax.swing.JLabel RegisterPasswordLabel;
    private javax.swing.JLabel RegisterSuccessLabel;
    private javax.swing.JTextField RegisterUserNameField;
    private javax.swing.JLabel RegisterUserNameLabel;
    // End of variables declaration//GEN-END:variables
}
