/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sauravyash.catalogueviewer.CatalogueWindow;

import com.sauravyash.catalogueviewer.CatalogueAudioPlayer;
import com.sauravyash.catalogueviewer.CatalogueViewer;
import com.sauravyash.catalogueviewer.userdatabase.NoRatingsException;
import com.sauravyash.catalogueviewer.userdatabase.RatingDB;
import java.io.File;
import java.io.IOException;
import org.json.simple.parser.ParseException;

/**
 * This is a full screen view of an item and provides the voting mechanism.
 * @author Yash
 */
public class ItemCardPanel extends javax.swing.JPanel {
    /**
     * The file for the back button image.
     */
    private CatalogueItem item;
    private CatalogueAudioPlayer audioPlayer;
    private File BackButtonImage = new File(CatalogueViewer.ResourcesFolder, "BackArrow.png");
    
    /**
     * The constructor that creates a new instance of the item card JPanel.
     * @param item The item to display in full detail
     */
    public ItemCardPanel(CatalogueItem item) {
        this.item = item;
        InitItemCard();
    }
    
    /**
     * This initializes all of the components and starts the sound.
     */
    private void InitItemCard(){
        initComponents();
        Utilities.LoadImageInJButton(BackButton, BackButtonImage);
        ImageLabel.setSize(512, 512);
        Utilities.LoadImageInJLabel(ImageLabel, item.image);
        TitleLabel.setText(item.title);
        SubtitleLabel.setText(item.subtitle);
        PriceLabel.setText("$" + String.format("%.2f", item.price).trim());
        DescriptionLabel.setText(ConvertToMultiline(item.description));
        try {
            AvgStarsLabel.setText("Liked By: " + RatingDB.GetPercentRating(item.title, CatalogueViewer.Catalogue.Title) + "%");
        } 
        // ignore 
        catch (NoRatingsException | ParseException | IOException ex) {
            AvgStarsLabel.setText("Rating: N/A");
        }
        
        StarRatingPanel.add(new RatingPanel(item));
        if (item.audio != null) {
            audioPlayer = new CatalogueAudioPlayer(item.audio);
            audioPlayer.start();
        }
        else System.err.println("no audio");
    }
    
    private static String ConvertToMultiline(String orig) {
        return "<html>" + orig.replaceAll("\n", "<br>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ImageLabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        ImageMetadataPanel = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        SubtitleLabel = new javax.swing.JLabel();
        DescTitleLabel = new javax.swing.JLabel();
        DescriptionLabel = new javax.swing.JLabel();
        PriceLabel = new javax.swing.JLabel();
        AvgStarsLabel = new javax.swing.JLabel();
        UserRatingPanel = new javax.swing.JPanel();
        UserRateMeLabel = new javax.swing.JLabel();
        StarRatingPanel = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(ImageLabel, gridBagConstraints);

        BackButton.setText("←");
        BackButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BackButton.setMaximumSize(new java.awt.Dimension(50, 50));
        BackButton.setMinimumSize(new java.awt.Dimension(50, 50));
        BackButton.setPreferredSize(new java.awt.Dimension(50, 50));
        BackButton.setSize(new java.awt.Dimension(50, 50));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 50, 20);
        add(BackButton, gridBagConstraints);

        ImageMetadataPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        ImageMetadataPanel.setLayout(new java.awt.GridBagLayout());

        TitleLabel.setBackground(new java.awt.Color(153, 0, 153));
        TitleLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        TitleLabel.setText("Title");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 35);
        ImageMetadataPanel.add(TitleLabel, gridBagConstraints);

        SubtitleLabel.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        SubtitleLabel.setText("Subtitle");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 35);
        ImageMetadataPanel.add(SubtitleLabel, gridBagConstraints);

        DescTitleLabel.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        DescTitleLabel.setText("Description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        ImageMetadataPanel.add(DescTitleLabel, gridBagConstraints);

        DescriptionLabel.setText("Desc....");
        DescriptionLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        ImageMetadataPanel.add(DescriptionLabel, gridBagConstraints);

        PriceLabel.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        PriceLabel.setText("price");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(15, 35, 15, 0);
        ImageMetadataPanel.add(PriceLabel, gridBagConstraints);

        AvgStarsLabel.setText("avg stars");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 35, 10, 0);
        ImageMetadataPanel.add(AvgStarsLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(ImageMetadataPanel, gridBagConstraints);

        UserRatingPanel.setLayout(new java.awt.GridBagLayout());

        UserRateMeLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        UserRateMeLabel.setText("Rate this Album: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        UserRatingPanel.add(UserRateMeLabel, gridBagConstraints);

        StarRatingPanel.setMaximumSize(new java.awt.Dimension(200, 50));
        StarRatingPanel.setPreferredSize(new java.awt.Dimension(200, 50));
        StarRatingPanel.setSize(new java.awt.Dimension(200, 50));
        StarRatingPanel.setLayout(new java.awt.GridLayout(1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.5;
        UserRatingPanel.add(StarRatingPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 100, 0);
        add(UserRatingPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        CatalogueWindowFrame.ShowMainMenu();
        this.getParent().remove(this);
        if (audioPlayer != null) audioPlayer.StopPlaying();
        CatalogueWindowFrame.menuplayer.togglePause();
    }//GEN-LAST:event_BackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvgStarsLabel;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel DescTitleLabel;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JPanel ImageMetadataPanel;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JPanel StarRatingPanel;
    private javax.swing.JLabel SubtitleLabel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel UserRateMeLabel;
    private javax.swing.JPanel UserRatingPanel;
    // End of variables declaration//GEN-END:variables
}
