/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sauravyash.catalogueviewer.CatalogueWindow;

import com.sauravyash.catalogueviewer.CatalogueViewer;
import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.font.TextAttribute;
import java.io.File;
import java.util.Map;
import javax.swing.JLabel;

/**
 * The individual panels for displaying the items in the main menu.
 * @author Yash
 */
public class ItemPanel extends javax.swing.JPanel {
    
    /**
     * The object that is visually represented.
     */
    private CatalogueItem RawObject;

    /**
     * The constructor for the Item Panel
     * @param item the item chosen to be displayed
     */
    public ItemPanel(CatalogueItem item) {
        RawObject = item;
        Init();
        TitleLabel.setText(item.title);
        SubtitleLabel.setText(item.subtitle);
        PriceLabel.setText("$" + String.format("%.2f", item.price).trim());
        Utilities.LoadImageInJLabel(ImageLabel, item.image);
    }
    
    /**
     * Initializes the components, images and mouse events for the image & title.
     */
    private void Init(){
        initComponents();
        Utilities.LoadImageInJButton(AddToCartButton, new File(CatalogueViewer.ResourcesFolder, "addtocart.png"));
        
        MouseAdapter mouseAdapter;
        mouseAdapter = new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                for (Frame c: CatalogueWindowFrame.getFrames()){
                    try {
                        CatalogueWindowFrame frame = (CatalogueWindowFrame) c;
                        frame.LoadItemCard(RawObject);
                    } catch (java.lang.ClassCastException e) {
                        // Ignore if frame is not main catalogue window (as it cannot be cast)
                    }
                }
            }
            
            @Override
            public void mouseEntered(MouseEvent me){
                JLabel label = TitleLabel;
                label.setForeground(Color.BLUE);
                Font font = label.getFont();
                Map attributes = font.getAttributes();
                attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON); 
                label.setFont(font.deriveFont(attributes));
            }
            
            @Override
            public void mouseExited(MouseEvent me){
                JLabel label = TitleLabel;
                label.setForeground(Color.black);
                Font font = label.getFont();
                Map attributes = font.getAttributes();
                attributes.put(TextAttribute.UNDERLINE, null); 
                label.setFont(font.deriveFont(attributes));
            }
        };
        
        ImageLabel.addMouseListener(mouseAdapter);
        TitleLabel.addMouseListener(mouseAdapter);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ImageLabel = new javax.swing.JLabel();
        TitleLabel = new javax.swing.JLabel();
        SubtitleLabel = new javax.swing.JLabel();
        PriceLabel = new javax.swing.JLabel();
        AddToCartButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        ImageLabel.setText(" ");
        ImageLabel.setMaximumSize(new java.awt.Dimension(400, 400));
        ImageLabel.setMinimumSize(new java.awt.Dimension(50, 50));
        ImageLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        ImageLabel.setSize(new java.awt.Dimension(180, 180));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.ipady = 75;
        add(ImageLabel, gridBagConstraints);

        TitleLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        TitleLabel.setText("title");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(TitleLabel, gridBagConstraints);

        SubtitleLabel.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        SubtitleLabel.setText("sub");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(SubtitleLabel, gridBagConstraints);

        PriceLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        PriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PriceLabel.setText("$0");
        PriceLabel.setToolTipText("Price");
        PriceLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(PriceLabel, gridBagConstraints);

        AddToCartButton.setText(" ");
        AddToCartButton.setSize(new java.awt.Dimension(20, 20));
        AddToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToCartButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(AddToCartButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Adds 1x represented item to the cart
     * @param evt ignored
     */
    private void AddToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToCartButtonActionPerformed
        // TODO add your handling code here:
        NavigationBarPanel.cart.AddItem(RawObject);
    }//GEN-LAST:event_AddToCartButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToCartButton;
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JLabel SubtitleLabel;
    private javax.swing.JLabel TitleLabel;
    // End of variables declaration//GEN-END:variables
}
