/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sauravyash.catalogueviewer.CatalogueWindow;

import com.sauravyash.catalogueviewer.CatalogueViewer;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 * The Panel used to identify the catalogue name, view the 
 * cart, Log out, change catalogue, and quit.
 * @author Yash
 */
public class NavigationBarPanel extends javax.swing.JPanel {

    /**
     * The Shopping Cart Menu Bar Instance.
     */
    public static ShoppingCart cart = new ShoppingCart();
    
    /**
     * The constructor for the Navigation Bar.
     */
    public NavigationBarPanel() {
        initComponents();
        InitImages();
        CatalogueTitle.setText(CatalogueViewer.Catalogue.Title);
        WelcomeUserLabel.setText("Welcome " + CatalogueViewer.UserData.FirstName);
        InitMenubar();
    }
    
    /**
     * Start the logging out process.
     * 
     * Displays a confirmation pane before logging out.
     */
    private void LogOut() {
        int input = JOptionPane.showConfirmDialog(null, "Are you sure that you want to log out?");
        // User answers yes
        if(input==0) {
            CatalogueViewer.LogOut();
            CatalogueWindowFrame.DestroySelf(); 
        }
        // User answers
        // No & cancel options (1&2) are ignored   
    }
    
    /**
     * Initialize the Menu bar Components.
     */
    private void InitMenubar(){
        cart.AttachTo(this);
        JMenuBar menuBar = new JMenuBar();
        JMenu menu = new JMenu("▼");
        menuBar.add(menu);
        
        JMenuItem OpenCatMenuItem = new JMenuItem("Open Catalogue", KeyEvent.VK_T);
        OpenCatMenuItem.addActionListener((ActionEvent ae) -> {
            CatalogueWindowFrame.DestroySelf();
            CatalogueViewer.OpenSelectorWindow();
        });
        
        JMenuItem LogOutMenuItem = new JMenuItem("Log Out", KeyEvent.VK_T);
        LogOutMenuItem.addActionListener((ActionEvent ae) -> {
            LogOut();
        });
        
        JMenuItem QuitMenuItem = new JMenuItem("Quit", KeyEvent.VK_T);
        QuitMenuItem.addActionListener((ActionEvent ae) -> {
            CatalogueViewer.ShutDown();
        });
        
        menu.add(OpenCatMenuItem);
        menu.add(LogOutMenuItem);
        menu.add(QuitMenuItem);
        //MenuPanel.
        add(menuBar);
    }
    
    /**
     * Loads the Catalogue Icon.
     */
    private void InitImages(){
        Utilities.LoadImageInJLabel(CatalogueIconLabel, CatalogueViewer.Catalogue.Icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        CatalogueIconLabel = new javax.swing.JLabel();
        CatalogueTitle = new javax.swing.JLabel();
        WelcomeUserLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        CatalogueIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CatalogueIconLabel.setText(" ");
        CatalogueIconLabel.setSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(CatalogueIconLabel, gridBagConstraints);

        CatalogueTitle.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        CatalogueTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CatalogueTitle.setText("CatalogueTitle");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 150);
        add(CatalogueTitle, gridBagConstraints);

        WelcomeUserLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        WelcomeUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeUserLabel.setText("Welcome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 150, 0, 50);
        add(WelcomeUserLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CatalogueIconLabel;
    private javax.swing.JLabel CatalogueTitle;
    private javax.swing.JLabel WelcomeUserLabel;
    // End of variables declaration//GEN-END:variables

}
